language: node_js
node_js:
- 7.2.1
script: npm run test
before_script:
- npm install
env:
  global:
    secure: yGMX25xTnYXnmGhlR5H8MUZXFpOz2o3A8z6nPEqkopQgzf/I5rUMKluToPiq3B4+LbTu0x8gye+ziyRZCGo9rABNmmuAPQcwf4/6CzXvSIHJCxg6DSIKpdwbfDybD7/98RHQy7UWhAglwc3n1y83IIo24ze0iUR+vEf45Ebl+7qYZKHbsWtG5q8I/hGAJbmWvA/ehqnWYP8SPskhH9lxut1m5dFtz7ebteElU0joCwS5orKscBX3FhFIBjAF0dT4od92eO8ACKTamntHAEhtgORROMcF/mOSHaDrm5xSBRq+zmruRw6lvy3ldF84/Rs0PXfNYlARXeBZDtxUnhPbZi73nNbJxXWQK5lkJOLgJh81Vc7ZyPPiY3SMA9Gtz7JT1JSzeXgz8y5rHsbqqOJ7PHFozJSUBQf5JQKm6rcR8VZRTjPJOsOxeDFd6at2mrhBKC8/kCIeJ+NRv0SyVuMXKiTEDV9EEFR1tFJbVO+kMc6uyUSfc5bi/WooFSoJGr54wtr59+QaKVOPiWDH/gk/5UgPpURBqfJDXYdu30x4pZaKIwh8EByB6F9MUM+FRk9Ii32QhwSYurMycmQLSgi4oNcWRcih4E3tGpoQM1SLV/V+EtYIC7Rm+1GV9H304Vgu5OoxmXSvWB33IbcI46KMHn3utj9VVlBwsAXn77pTYHI=
